homepage:
    path: /
    defaults: { _controller: MelodycodeFossdroidBundle:Homepage:index }  
client_apps:
    path: /client/apps
    defaults: {_controller: MelodycodeFossdroidBundle:Client:apps}
client_subs:
    path: /client/subs
    defaults: {_controller: MelodycodeFossdroidBundle:Client:subs}
client_account:
    path: /client/account
    defaults: {_controller: MelodycodeFossdroidBundle:Client:account}        
category:
    path: /c/{slug}/
    defaults: { _controller: MelodycodeFossdroidBundle:Category:index }
bundle:
    path: /b/{slug}/
    defaults: { _controller: MelodycodeFossdroidBundle:Bundle:index }
login:
    path: /login
    defaults: { _controller: MelodycodeFossdroidBundle:Security:login }  
login_check:
    path: /login_check           
logout:
    path: /logout    
category_whats_new:
    path: /c/{slug}/whats_new.html
    defaults: { _controller: MelodycodeFossdroidBundle:Category:whatsnew }
search:
    path: /s.html
    defaults: { _controller: MelodycodeFossdroidBundle:Search:index }
application:
    path: /a/{slug}.html
    defaults: { _controller: MelodycodeFossdroidBundle:Application:index }
application_download:
    path: /a/{slug}.apk
    defaults: { _controller: MelodycodeFossdroidBundle:Application:download }
application_:
    path: /a/{slug}
    defaults: { _controller: MelodycodeFossdroidBundle:Application:_index }
application_buy:
    path: /a/{slug}/buy
    defaults: { _controller: MelodycodeFossdroidBundle:Application:buy}    
s:
    path: /s/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true