melodycode_fossdroid:
    resource: "@MelodycodeFossdroidBundle/Resources/config/routing.yml"
    prefix:   /store
    
iris_dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard